language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t almattttt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true almattttt/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucker_name: "elasticbeanstalk-eu-central-1-509075217623"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
