language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t almattttt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true almattttt/docker-react npm run test